name: React Nightly Build

on:
  schedule:
    cron: '30 4 * * *'
  
  workflow_dispatch:

jobs:
  nightly-build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Code
          uses: actions/checkout@v4
        
        - name: Log the Time
          run: echo "Starting nightly maintenance task..."
        
        - name: Install & Test
          run: |
            npm install
            npm test